### ISSUE TITLE
mt_path not found

### ISSUE THREAD

**Issue by emikowaight** [nhgritctran/PheTK#3]
Hello, I wanted to use this PheTK tool to conduct a PheWAS examining different variants in the ALDH2 gene. I tried to replace the information in the demo with the correct genotype I am looking for, but I get a fatal error when I try to run the program. From the error message it looks like there is an issue in the mt_path read matrix, and I am unsure is something was changed in the default path on all of us? I have copied the code I ran and the initial output error message. 

The last part of the error message: 
Hail version: 0.2.126-ee77707f4fab
Error summary: UnsupportedFileSystemException: No FileSystem for scheme "gs"

FatalError                                Traceback (most recent call last)
Cell In[3], line 7
      4 cohort = Cohort(platform="aou", aou_db_version=7)
      6 # generate cohort by genotype
----> 7 cohort.by_genotype(
      8     chromosome_number=12,
      9     genomic_position=111803962,
     10     ref_allele="G",
     11     alt_allele="A",
     12     case_gt="0/1",
     13     control_gt="0/0",
     14     reference_genome="GRCh38",
     15     mt_path=None,
     16     output_file_name="aldh2_test1_cohort.csv"
     17 )

File ~/.local/lib/python3.10/site-packages/PheTK/Cohort.py:136, in Cohort.by_genotype(self, chromosome_number, genomic_position, ref_allele, alt_allele, case_gt, control_gt, reference_genome, mt_path, output_file_name)
    133 variant = hl.parse_variant(variant_string, reference_genome=reference_genome)
    135 # load and filter matrix table
--> 136 mt = hl.read_matrix_table(mt_path)
    137 mt = mt.filter_rows(mt.locus == hl.Locus.parse(locus))
    138 if mt.count_rows() == 0:

**Comment by nhgritctran** [comment]
> Error summary: UnsupportedFileSystemException: No FileSystem for scheme "gs"

This error means that your system does not recognize Google Cloud Storage system.

Based on your code, you are trying to extract genotype data from _All of Us_, but it seemed you are running PheTK outside of the _All of Us_ researcher workbench. To use any _All of Us_ related features, user must be registered as a researcher with the _All of Us_ Research Program, and run PheTK within their workbench. More information can be found here: https://www.researchallofus.org/

**Comment by emikowaight** [comment]
I was actually running the code within the All of Us researcher workbench, so that is why I was confused as to why it was not working.

**Comment by emikowaight** [comment]
<img width="1323" alt="Screenshot 2024-05-05 at 6 11 25 PM" src="https://github.com/nhgritctran/PheTK/assets/162065390/b7fc3b44-f6de-435a-b312-b01707c34827
<img width="1327" alt="Screenshot 2024-05-05 at 6 11 39 PM" src="https://github.com/nhgritctran/PheTK/assets/162065390/e4ffa6c9-27bb-40db-bfad-00f9a3648c52">
">

**Comment by nhgritctran** [comment]
Thank you for the clarification. That is a bit weird because the initial `No FileSystem for scheme "gs"` error should not happen running on _All of Us_ because _All of Us_ uses Google Cloud buckets for project long term storage - that is why I guessed you were running PheTK outside of it.

The provided error screenshot was truncated so I cannot tell what the exact error was, but it did appear to be related to `mt_path`. A possibility is you are running an older version of PheTK (version 0.1.37 or earlier; current version is 0.1.39) where the default matrix table path was not updated.

Could you please lease provide more details on:
- Your current PheTK version by running `!pip show PheTK | grep Version` in a notebook cell. 
- Full error details of the above screenshot.
- A screenshot or details of the cloud environment settings.

I just tested PheTK v0.1.39 on a dataproc VM on _All of Us_ and successfully generated a cohort with your settings above.
<img width="559" alt="Screenshot 2024-05-05 at 7 50 03 PM" src="https://github.com/nhgritctran/PheTK/assets/123414601/d607782c-212f-4654-ac99-a54c919bc2b8">

**Comment by emikowaight** [comment]
<img width="659" alt="Screenshot 2024-05-05 at 7 03 25 PM" src="https://github.com/nhgritctran/PheTK/assets/162065390/1b0fc732-489c-4611-85e3-cd5e73b9fe24">
The version is listed as 0.1.38, how do I upgrade to the 39 version? Is that what is causing the error?

**Comment by emikowaight** [comment]
<img width="1045" alt="Screenshot 2024-05-05 at 7 05 27 PM" src="https://github.com/nhgritctran/PheTK/assets/162065390/080d34bc-4572-4e72-a903-00ee83a053d4
<img width="1340" alt="Screenshot 2024-05-05 at 7 05 39 PM"
<img width="860" alt="Screenshot 2024-05-05 at 7 05 49 PM" src="https://github.com/nhgritctran/PheTK/assets/162065390/f50cd625-108f-466d-bc79-8f8e435aa57a">
 src="https://github.com/nhgritctran/PheTK/assets/162065390/34f14a39-6908-4808-abce-acc96e21889f">
">

**Comment by emikowaight** [comment]
I added three screenshots because the error was so long I could not fit it into 1

**Comment by nhgritctran** [comment]
0.1.38 should have updated mt_path already. Version is not the case here, but you can update PheTK following instruction on  this GitHub by running `!pip uninstall PheTK -y && pip install PheTK` in your notebook and then restarting kernel.

What is your cloud environment configuration? i.e., standard VM or dataproc? You can check by clicking on the Jupyter icon on the vertical panel on the right side.

You are probably running `.by_genotype()` method on a standard VM instead of dataproc VM. This method uses hail to interact with the _All of Us_ hail matrix tables containing variant data. When running hail, on standard VM, you can get that "gs" error as well.

You can look at this link for more information on customizing your Jupyter environment https://support.researchallofus.org/hc/en-us/articles/18278298730644-Using-customizing-and-optimizing-Jupyter-cloud-environments

**Comment by nhgritctran** [comment]
This dataproc requirement is already mentioned on this GitHub readme:

<img width="810" alt="Screenshot 2024-05-05 at 8 27 56 PM" src="https://github.com/nhgritctran/PheTK/assets/123414601/666ffb6d-7199-4a3a-a100-4f1bc797f0c9">
